README.md, internal/cmds/builder.go, internal/cmds/builder_test.go
fix https://github.com/rueian/rueidis/issues/11
=> feat: allow building arbitrary commands

client_test.go, hack/cmds/gen.go, internal/cmds/cmds.go, internal/cmds/cmds_test.go, internal/cmds/gen.go, internal/cmds/gen_test.go, lru.go, lru_test.go, pipe.go, pipe_test.go
Request by https://github.com/rueian/rueidis/issues/60
=> Mget cache

client.go, client_test.go, cluster.go, cluster_test.go, lua_test.go, mux.go, mux_test.go, pipe.go, pipe_test.go, rueidis.go, rueidisotel/trace.go, rueidisotel/trace_test.go, sentinel.go, sentinel_test.go
WIP https://github.com/rueian/rueidis/issues/60
=> feat: add DoMultiCache

mux.go, mux_test.go, pipe.go, pipe_test.go, rueidiscompat/adapter.go
Addressing https://github.com/rueian/rueidis/issues/77
=> Fix blocking heartbeat

hack/cmds/commands_ai.json, hack/cmds/commands_bloom.json, hack/cmds/commands_json.json, hack/cmds/commands_search.json, hack/cmds/commands_timeseries.json, internal/cmds/gen.go, internal/cmds/gen_test.go
RedisGraph 2.8.19
RedisBloom 2.2.8
RediSearch 2.4.14
RedisTimeSeries 1.6.17
RedisAI 1.2.7
RedisGears 1.2.5
RedisJSON 2.2.0
=> Most recently released redis modules

rueidislock/README.md, rueidislock/lock.go, rueidislock/lock_test.go
=> Rueidislock setpx

docker-compose.yml
=> Up DragonflyDB to the v1.1.2

rueidishook/README.md
minor fix for hook README 
@rueian Thanks
=> fix: hook README

.github/release-drafter-config.yml, .github/workflows/release-drafter.yml
Adding the release drafter, as used by other redis clients
=> Release drafter

cache.go, cache_test.go
Provide `NewSimpleCacheAdapter` function converting a `SimpleCache`, which is just a KV store interface, into complex `CacheStore`
=> feat: NewSimpleCacheAdapter converts a SimpleCache into CacheStore

cluster.go, cluster_test.go
=> fix: allow connect to a cluster having no slots

cluster.go, cluster_test.go, rueidis.go
=> perf: reduce unnecessary CLUSTER SLOTS sent

hack/cmds/commands_sentinel.json, internal/cmds/cmds.go, internal/cmds/gen_sentinel.go, internal/cmds/gen_sentinel_test.go, rueidis.go, sentinel.go, sentinel_test.go
Hi, This is my suggested implementation for a read-only replica client (#132)  for **sentinel** Redis setup. Please share your thoughts on this implementation. If it's OK with you I can write the unit tests to cover what's changed.
=> Add Sentinel readonly replica support

pipe.go, pipe_test.go, rueidis.go
=> Feat: Support client no touch in ClientOptions struct

rueidisotel/trace.go, rueidisotel/trace_test.go
@rueian  maybe this can be option? Thanks
=> feat: add traceProvider && meterProvider option

rueidislock/README.md, rueidislock/lock.go, rueidislock/lock_test.go
=> feat: let rueidislock work without client-side caching

rueidislock/lock.go, rueidislock/lock_test.go
address https://github.com/redis/rueidis/discussions/240
=> Retry false locker closed

sentinel.go
Fix IPv6 joining with port bug, which affect Redis Sentinel.
**Bug:**
If we got IP address of master is `fdca:4b8:c25:2c15:010:1589:8670:756c` and port `123`. Joining via `fmt.Sprintf("%s:%s", ip,port)` lead to incorrect ip + port adress `fdca:4b8:c25:2c15:010:1589:8670:756c:123`.
**Solution:**
Use `net.JoinHostPort`, which try to determine IPv4 or IPv6 
https://pkg.go.dev/net#JoinHostPort
=> fix: Use net.JoinHostPort to join ip to handle IPv6

cluster.go, cluster_test.go, pipe.go, pipe_test.go
related to https://github.com/redis/rueidis/issues/278
The old implementation of `clusterclient.DoMulti()` and `clusterclient.DoMultiCache()` performs poorly when the number of commands passed in is large. That is because those commands will be grouped into their key slots, resulting in many small chunks being parallelly fired. If one's CPU has limited concurrency, then the performance of these functions degrades significantly.
The new implementation grouping commands into their underlying connections, resulting in a minimum number of chunks to be parallelly fired. Even with limited concurrency, this implementation will have a better performance.
Before:
```
Benchmark
Benchmark/GET_DoMulti
Benchmark/GET_DoMulti-10         	     144	   8138918 ns/op	  484360 B/op	    5015 allocs/op …
```
=> perf: boost DoMulti/Cache of the cluster by grouping cmds to conns, not slots

resp.go
Before:
```
goos: darwin
goarch: arm64
pkg: rueidis-benchmark/redjet
BenchmarkName
BenchmarkName/rueidis
BenchmarkName/rueidis-10         	    7810	    156033 ns/op	    9030 B/op	     202 allocs/op
PASS
```
After:
```
goos: darwin
goarch: arm64
pkg: rueidis-benchmark/redjet
BenchmarkName
BenchmarkName/rueidis
BenchmarkName/rueidis-10         	    7942	    155897 ns/op	    8627 B/op	     102 allocs/op
PASS
```
Source:
```go
func Benchmark(b *testing.B) {
loop := 100
client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6379"}})
panic(err)
}
payload1K = strings.Repeat("x", 1024)
cmds := make(rueidis.Commands, 0, loop)
for i := 0; i < loop; i++ {
cmds = append(cmds, client.B().Set().Key("foo").Value(payload1K).Build().Pin())
}
b.Run("rueidis", …
```
=> perf: reduce allocs/op by dropping the usages of strconv.Itoa()

rueidislock/lock.go, rueidislock/lock_test.go
Resolves https://github.com/redis/rueidis/discussions/300
=> fix: hanging in the cancel fn of rueidislock.TryWithContext

pipe.go
conn.SetDeadline can occupy a large portion of a CPU benchmark profile. Though this is rare, I have seen it occupy ~10% of CPU time in benchmark several times.
=> perf: reduce unnecessary calls to conn.SetDeadline

pipe.go, pipe_test.go
match lowercase hello command.
=> feat: match lowercase hello command

client.go, cluster.go, cmds.go, lua_test.go, mock/client.go, rueidis.go, rueidishook/hook.go, rueidisotel/trace.go, sentinel.go
Resolves https://github.com/redis/rueidis/issues/314
=> feat: export command builder type

rueidis.go
related to https://github.com/redis/rueidis/issues/314
=> feat: introduce CoreClient as a shared interface between the Client and the DedicatedClient

message.go, message_test.go
Related to https://github.com/redis/rueidis/issues/319
=> feat: supports new RESP3 FT.SEARCH

message.go, message_test.go, om/cursor.go, om/hash.go, om/json.go
Resolves https://github.com/redis/rueidis/issues/319
=> feat: supports new RESP3 FT.AGGREGATE and RedisMessage.AsFtAggregate

.circleci/config.yml, internal/cmds/builder.go, internal/cmds/builder_put.go, internal/cmds/builder_put_121.go
Resolves https://github.com/redis/rueidis/issues/312
=> refactor: use clear() to eagerly clean the builder slices

README.md, url.go, url_test.go
Solves https://github.com/redis/rueidis/issues/317
=> feat: rueidis.ParseURL and rueidis.MustParseURL

client.go, client_test.go, cluster.go, cluster_test.go, rueidis.go
fixes https://github.com/redis/rueidis/issues/359
=> feat: detect misuse of client.Dedicate()

ring.go
Fixes https://github.com/redis/rueidis/issues/364
=> fix: enable gc to eagerly recycle used elements on ring queues

client_test.go, cluster.go, cluster_test.go, internal/cmds/cmds.go, mux.go, mux_test.go, pipe.go, pipe_test.go, rueidiscompat/adapter.go, rueidiscompat/adapter_test.go, rueidiscompat/command.go, rueidiscompat/command_test.go
=> feat: use CLUSTER SHARDS 

rueidislock/lock.go, rueidislock/lock_test.go
=> fix: rueidislock's infinite loops when receiving bulk invalidations

README.md, url.go, url_test.go
=> feat: support multiple addresses #317

client_test.go, cluster.go, cluster_test.go, dockertest.sh, mux.go, pipe.go, sentinel.go, singleflight.go, singleflight_test.go
=> fix: refresh AWS shards periodically

hack/cmds/commands.json, internal/cmds/gen_server.go, internal/cmds/gen_server_test.go
It looks like this isn't quite working at the moment, I may have misconfigured the JSON, or else I may have to look into the code generation next week to see exactly what is going on.
=> Replica one of arguments

cluster.go, cluster_test.go
resolve: https://github.com/redis/rueidis/issues/397
randomly pick one of replicas for a slot
=> refactor: distribute slots to replicas

lru.go, lru_test.go, pubsub.go, ring.go
=> fix: atomic alignment issue on 32bit arch

om/README.md, om/conv.go, om/hash.go, om/hash_test.go, om/json.go, om/json_test.go, om/schema.go, om/schema_test.go
Ref: https://github.com/redis/rueidis/issues/383
=> feat: allow setting expiry on om entities by adding an exat field

rueidis.go
=> feat: let clusterclient respect the option.PipelineMultiplex

mux_test.go, pipe.go, pipe_test.go, rueidis.go, rueidis_test.go
Resolves https://github.com/redis/rueidis/issues/419
=> fix: correct CLIENT SETINFO connection setup

rueidiscompat/adapter.go
=> fix: rueidiscompat's ZPopMax and ZPopMin with count 1

rueidisotel/README.md
Sorry, I've forgotten adding document for `rueidisotel.NewClient`.
=> doc: add rueidisotel client metrics

rueidisotel/README.md
This closes https://github.com/redis/rueidis/issues/442
=> doc: Modify rueidisotel documentation

rueidisprom/go.mod
Introduce a new subpackage for adding support for prometheus metrics in Rueidis.
Add a separate go.mod file for it.
#444
=> Introduce rueidisprom subpackage

NOTICE
=> Update copyright year

rueidiscompat/adapter.go, rueidiscompat/adapter_test.go, rueidiscompat/command.go
This PR implemented adapter for `go-redis` `JSONCmdable`.
=> Feat: Align `go-redis` `JSONCmdable`

go.mod, mock/go.mod, rueidishook/go.mod
Hello, this change addresses #453.
=> refactor: move uber/mock dependency to submodules

.circleci/config.yml, README.md, dockertest.sh, rueidisprob/README.md, rueidisprob/bloomfilter.go, rueidisprob/bloomfilter_test.go, rueidisprob/go.mod, rueidisprob/go.sum, rueidisprob/index.go
discussion: https://github.com/redis/rueidis/discussions/486
standard bloom filter for `rueidisprob`
=> feat: rueidisprob package and standard bloom filter

message.go, message_test.go
Hi. I added .AsBoolSlice() as requested
=> Add RedisResult.AsBoolSlice() #499

message.go, message_test.go
Resolves: https://github.com/redis/rueidis/discussions/506
=> feat: parse FT.SEARCH WITHSCORES in AsFtSearch()

README.md
=> docs: DecodeSliceOfJSON in README.md

rueidishook/hook.go, rueidishook/hook_test.go
Resolves https://github.com/redis/rueidis/issues/527
=> feat: add NewErrorResult() to rueidishook

cluster.go, cluster_test.go
Fixes https://github.com/redis/rueidis/issues/543
=> fix: panic when initializing rueidis.Client while Redis Cluster is not available

rueidislock/lock.go, rueidislock/lock_test.go
Add a new ForceWithContext method to rueidislock.
=> feat: impl ForceWithContext in rueidislock

rueidiscompat/command_test.go
* Added test to increase coverage for GeoSearchQuery
* Added test to increase coverage for String method
* Added test to increase coverage for XAutoClaimCmd SetErr
=> minor tests for command.go under rueidis.compat

pipe.go
https://github.com/redis/rueidis/issues/156#issuecomment-2167410921
=> perf: set 1s limit for graceful shutdown to avoid waiting for a stuck redis

internal/cmds/cmds.go, pipe.go, pipe_test.go
=> feat: send DISCARD command when conn recycled

cluster.go, cluster_test.go
what i found is when got "MOVED" to specific slot, many refreshes are possible. so we update "pslots" and "rslots" when got "MOVED".
"ASK" also triggers many refreshes but it should not change "pslots" and "rslots". because importing node may not serve some items which are migrated yet.
=> enhancement: mitigate refresh storm

rueidisprob/bloomfilter.go
sorry, i forgat to remove unused code
=> chore: clean up unused code

cluster.go
Related to https://github.com/redis/rueidis/issues/587
=> fix: set timeout on refreshing cluster slots to avoid being stuck

docker-compose.yml, rueidiscompat/adapter.go, rueidiscompat/adapter_test.go, rueidiscompat/command.go, rueidiscompat/pipeline.go, rueidiscompat/pipeline_test.go
Resolves https://github.com/redis/rueidis/issues/607
=> feat: add HExpire, HPExpire, HTTL, and HPTTL to rueidiscompat

cluster.go
=> fix: panic on cluster redirection to the same host

pipe.go, pipe_test.go
Fix for blocking calls using ConnWriteTimeout whenever the context has a deadline set instead of the deadline. See https://github.com/redis/rueidis/issues/665
=> fix blocking call timeouts when context has a deadline

pool.go, pool_test.go
Fixes https://github.com/redis/rueidis/issues/675.
=> fix: prevent acquiring broken connections from the pool

.github/workflows/build.yml
Added concurrency config to build workflow to manage job execution and prevent overlapping runs for pull requests, improving CI/CD efficiency.
=> chore: enhance GitHub Actions workflow

rueidiscompat/adapter.go, rueidiscompat/pipeline.go
=> feat: Add ACLDelUser to rueidiscompat

rueidiscompat/adapter.go, rueidiscompat/pipeline.go
As title.
[issue #741](https://github.com/redis/rueidis/issues/741)
=> feat: Add ACLList to rueidiscompat

.github/workflows/build.yml
=> Add Go 1.24.0 to CI build matrix

rueidiscompat/adapter.go, rueidiscompat/adapter_test.go
=> fix: fix wrong usage of limit offset in rueidiscompat FTAggregateWithArgs, FTSearchWithArgs

rueidiscompat/adapter.go, rueidiscompat/command.go, rueidiscompat/pipeline.go, rueidiscompat/pipeline_test.go
=> feat: add SlowLogGet to rueidiscompat

rueidisprob/slidingbloomfilter.go, rueidisprob/slidingbloomfilter_test.go
=> improve the test coverage on rueidisprob

README.md
issue #785 
tried to fix as many as possible
=> Fix Lint Violations in README.md

rueidiscompat/go.mod, rueidiscompat/pubsub_test.go
Relates to #679 
Tests added:
- TestWithChannelSize
- TestSubscriptionString
- TestMessageString
=> Improve rueidiscompat test coverage

rueidiscompat/util_test.go
Add util_test.go file to cover util funcs.
=> Improve test coverage for rueidiscompat

pipe.go, pipe_test.go
fixes: https://github.com/redis/rueidis/issues/788
=> Fix NOAUTH Error: Ensure AUTH is Sent Before HELLO

pipe.go, pipe_test.go
=> Use timer for background PINGs instead of a long-live goroutine

rueidislock/README.md
https://redis.io/docs/latest/develop/use/patterns/distributed-locks/
=> [chore] Update broken url

mock/result.go, pipe.go
fixes #847
Tests executed successfully in the local env.
=> refactor: changed atomic.Value to atomic.Pointer in pipe

om/json.go
[#866](https://github.com/redis/rueidis/issues/866)
=> perf: replace json.NewDecoder with json.Unmarshal in the om package
