redis/rueidis

- README.md
- client.go
- client_test.go
- cluster.go
- mux.go
- mux_test.go
- pipe.go
- pipe_test.go
- rueidis.go
- sentinel.go
- sentinel_test.go
Support context deadline or cancellation with minimum overhead.
1. set context deadline to tcp connection while the `pipe` is in sync mode
2. check context channel if necessary while the `pipe` is in pipeline mode
> feat: support context cancellation under auto pipeline

- client_test.go
- cluster.go
- cluster_test.go
- internal/cmds/cmds.go
- lru.go
- lru_test.go
- mux.go
- mux_test.go
- pipe.go
- pipe_test.go
- redis_test.go
- rueidis.go
- rueidis_test.go
* reconnect redis if the MOVED redirects to the same host (ex: AWS MemoryDB)
* improve cluster failover by also trying all replicas and initial nodes in the original InitAddress
* fix borken pipe handling in sync mode
> fix: cluster failover to the same hostname and broken pipe in sync mode

- pipe.go
- rueidis.go
We use redis client caching with BCAST so we have to implement custom mechanism.
I also added p.background() because otherwise it didn't get called.
> Add CacheInvalidateCallback

- README.md
- hack/cmds/gen.go
- internal/cmds/builder.go
- internal/cmds/cmds.go
- internal/cmds/gen.go
- mux.go
- mux_test.go
- rueidis.go
- rueidis_test.go
```go
package main
import (
"context"
"fmt"
"math/rand"
"net/http"
"os"
"strconv"
"time"
"github.com/go-redis/redis/v9"
"github.com/prometheus/client_golang/prometheus"
"github.com/prometheus/client_golang/prometheus/promauto"
"github.com/prometheus/client_golang/prometheus/promhttp"
"github.com/rueian/rueidis"
)
func prepData(n int) []string {
data := make([]string, n)
for i := range data {
data[i] = strconv.Itoa(i)
}
rand.Shuffle(len(data), func(i, j int) { data[i], data[j] = data[j], data[i] })
return data
}
const (
keyCount  = 1000000
addr      = "10.140.0.52:6379"
)
func main() {
useGoRedis := os.Args[0] == "goredis"
concurrency, err := strconv.Atoi(os.Args[1])
panic(err)
}
rand.Seed(time.Now().UnixNano())
bucket := []float64{50, 100, 150, 200, 250, 300, 350, 400, …
```
> feat: multiplex single/sentinel client with default 4 connections to improve latencies

- README.md
- rueidishook/README.md
- rueidishook/hook.go
- rueidishook/hook_test.go
Allow users to intercept `rueidis.Client` interface by wrapping it with another `rueidishook.Hook` interface:
```go
package main
import (
"context"
"time"
"github.com/rueian/rueidis"
"github.com/rueian/rueidis/rueidishook"
)
type hook struct{}
func (h *hook) Do(client rueidis.Client, ctx context.Context, cmd rueidishook.Completed) (resp rueidis.RedisResult) {
return client.Do(ctx, cmd)
}
func (h *hook) DoMulti(client rueidis.Client, ctx context.Context, multi ...rueidishook.Completed) (resps []rueidis.RedisResult) {
return client.DoMulti(ctx, multi...)
}
func (h *hook) DoCache(client rueidis.Client, ctx context.Context, cmd rueidishook.Cacheable, ttl time.Duration) (resp rueidis.RedisResult) {
return client.DoCache(ctx, cmd, ttl)
}
func (h *hook) DoMultiCache(client rueidis.Client, ctx …
```
> feat: rueidishook

- pipe.go
- pipe_test.go
> fix: shutdown deadlock of pipe when its ring is full (#108)

- om/hash.go
- om/hash_test.go
- om/json.go
- om/json_test.go
- om/repo.go
Resolves #115
Add `SaveMulti` to `om. Repository`. Usage example:
```go
package main
import (
"context"
"fmt"
"github.com/rueian/rueidis"
"github.com/rueian/rueidis/om"
)
type obj struct {
Key string `json:"key" redis:",key"`
Ver int64  `json:"ver" redis:",ver"`
Val int64  `json:"val"`
}
func main() {
c, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6377"}})
panic(err)
}
defer c.Close()
repo := om.NewJSONRepository("obj", obj{}, c)
fmt.Println(repo.CreateIndex(context.Background(), func(schema om.FtCreateSchema) om.Completed {
return schema.FieldName("$.val").As("val").Numeric().Build()
}))
records := make([]*obj, 100000)
for i := range records {
records[i] = repo.NewEntity()
records[i].Val = int64(i)
}
for _, err = range …
```
> feat: om Repository.SaveMulti to batch saving multiple om records

- pipe.go
- pipe_test.go
also reduce unnecessary pings by checking the `recvs` counter.
> feat: ping redis proactively even when not pipelining

- pipe.go
- pipe_test.go
- rueidis.go
Relates #156 
Adds `MaxFlushDelay` option to `rueidis.ClientOption`:
```go
// MaxFlushDelay when greater than zero pauses pipeline write loop for some time (not larger than MaxFlushDelay)
// after each flushing of data to the connection. This gives pipeline a chance to collect more commands to send
// to Redis. Adding this delay increases latency, reduces throughput – but in most cases may significantly reduce
// application and Redis CPU utilization due to less executed system calls. By default, Rueidis flushes data to the
// connection without extra delays. Depending on network latency and application-specific conditions the value
// of MaxFlushDelay may vary, sth like 20 microseconds should not affect latency/throughput a lot but still
// produce notable CPU usage reduction under load. …
```
> Add MaxFlushDelay option

- message.go
- message_test.go
This PR actually removes almost all `RedisResult` memory allocation while delegating to `RedisMessage`. The previous memory allocation behavior can be considered a bug.
Given the following benchmark:
```go
func BenchmarkRueidisToString(b *testing.B) {
client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6379"}})
panic(err)
}
defer client.Close()
b.ReportAllocs()
b.ResetTimer()
b.RunParallel(func(pb *testing.PB) {
for pb.Next() {
_, _ = client.Do(context.Background(), client.B().Get().Key("Key").Build()).ToString()
}
})
b.StopTimer()
}
```
The old result is:
```
goos: darwin
goarch: arm64
BenchmarkRueidisToString
BenchmarkRueidisToString-10    	  385492	      3397 ns/op	     163 B/op	       2 allocs/op
PASS
```
The new result will be:
``` …
```
> perf: reduce 90% of RedisResult memory allocation while delegating to RedisMessage

- message.go
- message_test.go
Add `AsScanEntry` since there is no message function for SCAN series command, people need to parse cursor and elements by themself.
> feat(message): implement `AsScanEntry`

- message.go
- message_test.go
- rueidiscompat/adapter.go
- rueidiscompat/adapter_test.go
- rueidiscompat/command.go
- rueidiscompat/command_test.go
* ExpireTime
* PExpireTime
* SortRO
* HRandField
* HRandFieldWithValues
* BLMPop
* LMPop
* SInterCard
* BZMPop
* ZAddLT
* ZAddGT
* ZInterCard
* ZMPop
* ClientUnblock
* ClientUnblockWithError
* EvalRO
* EvalShaRO
* SPublish
* PubSubShardChannels
* PubSubShardNumSub
> feat: align rediscompat with go-redis v9, including

- rueidis.go
- rueidis_test.go
Allows for the ability to add a custom dial function as a ClientOption. This is useful for getting metrics on dials, such as dial latency, dial errors/successes, etc..
> add ClientOption.DialFn to manually create TCP/TLS connections

- mock/result.go
- mock/result_test.go
> fix: correct RESP3 map type generated by mock.RedisMap helper

- lua.go
- lua_test.go
- message.go
- message_test.go
RedisResult.RedisError() only returns Redis ERR message and ignores other errors, such as network errors. It is easily to be confused with RedisResult.Error(), which will return all errors and is the actual one that users should use.
By replacing RedisResult.RedisError with rueidis.IsRedisErr(), it now requires users to call RedisResult.Error() first, and checking the ok flag it returned.
fixes #229
> feat: replace RedisResult.RedisError() with rueidis.IsRedisErr() to avoid confusion

- helper.go
- helper_test.go
Regarding #239, I think using `parallelMget` for cached MGet helper functions will solve the issue. please let me know if anything else should be done.
> Use ParallelMGet for single client in MGetCache helper function

- pipe.go
- pipe_test.go
SUBSCRIBE/UNSUBSCRIBE in MULTI EXEC will cause wrong responses from Redis.
> fix: disallow SUBSCRIBE/UNSUBSCRIBE in MULTI/EXEC

- message_test.go
due to #262, return false when isRedisNil, isRedisErr faces wrapped error.
> test case : update message test case for wrapped error

- message.go
- message_test.go
- resp.go
This change is made to address issue [127](https://github.com/redis/rueidis/issues/271). Currently when a no-op type conversion happens as a result of calling To* or As* the error message produced looks like this
```
panic: redis message type : as map key is not supported
```
The RESP3 character that represents a 64 bit integer ':' is shown to be reason for the panic
With the current change applied, the error message would now look like this 
```
panic: redis message type int64 as map key is not supported
```
Current unit tests are covering the changes to the error messages in message.go, let me know if more tests are desired to add to coverage of the different types.
Notes for maintainers:
For this PR I decided to keep the change small while still addressing the root problem. I see that …
> Use type name in RedisMessage error instead of RESP3 character

- message.go
- message_test.go
This change is to add an AsGeosearch method to RedisResult and RedisMessage to convert Geosearch query results into the GeoLocation type that is available in go-redis. Geosearch responses can be tricky to parse as you can get two types back. A standard request like below
```golang
resp = client.Do(context.Background(), client.B().
Geosearch().
Key("cities").
Fromlonlat(76.1474, 43.0481).
Bybox(200).
Height(200).
Mi().
Build())
```
Will result in receiving an Array of BlobString where the contents are the geolocation names assigned when performing a GeoAdd insertion query
```
//Using github.com/davecgh/go-spew/spew to inspect the type
([]interface {}) (len=2 cap=2) {
(string) (len=8) "Syracuse",
(string) (len=6) "Albany"
}
```
However, if additional features are requested, then the data …
> Feature: Add AsGeosearch method for RedisResult

- internal/util/parallel.go
Program may be running on an N core machine but only allowed to use M cores via GOMAXPROCS=M. Spawning more than M CPU-bound goroutines just creates useless work for Go scheduler. It can also result in CPU throttling when limits are enforced by cgroups. See https://github.com/golang/go/issues/33803.
> perf: use runtime.GOMAXPROCS() to determine max concurrency

- helper.go
- helper_test.go
related to https://github.com/redis/rueidis/issues/278
Single Client Before
```
Benchmark
Benchmark/MGet
Benchmark/MGet-10         	    2770	    520576 ns/op	  310661 B/op	    1005 allocs/op
Benchmark/MGetCache
Benchmark/MGetCache-10    	    6554	    179813 ns/op	  370530 B/op	    1045 allocs/op
PASS
```
Single Client After
```
Benchmark
Benchmark/MGet
Benchmark/MGet-10         	    2749	    490253 ns/op	  310944 B/op	    1006 allocs/op
Benchmark/MGetCache
Benchmark/MGetCache-10    	   11476	    105266 ns/op	  471776 B/op	      55 allocs/op
PASS
```
---
Sentinel Client Before
```
Benchmark
Benchmark/MGet
Benchmark/MGet-10         	     135	   8403304 ns/op	  471670 B/op	    2281 allocs/op
Benchmark/MGetCache
Benchmark/MGetCache-10    	    6852	    150697 ns/op	  369290 B/op	    1042 …
```
> perf: speed up MGet/Cache/MSet heplers by grouping commands by connections instead of slots

- rueidis.go
- rueidis_test.go
👋 Hello
First thank you for this superb lib!
On a redis instance with one node, but spawned as a cluster (yes a cluster of one node), if we are using the rueidis default behaviour, we can connect to this redis instance (HELLO 3 is ok), but once we send a command, the redis cluster is flooded with `CLUSTER SLOTS` commands.
I was not able (and do not have time right now to dig further) to find the issue, I've seen we are looking at InitAddress and we should not flood `CLUSTER SLOTS` commands in for loop from `cluster.go/_refresh`, but I have not dag further.
The quick fix for us is to force rueidis to connect as a single redis instance.
I can understand you don't want to merge this PR since this is a dirty fix, no problem!
But I wanted to share this behaviour!
If someone has the same issue, …
> feat: force single client connection

- cluster.go
- cluster_test.go
Related to #284 described issue, this fix proposed by @rueian should fix the parsing of an empty slot IP on clusters of 1 node, whom node does not know his own IP.
> fix: cluster of 1 node with unknown ip

- client.go
- client_test.go
- cluster.go
- cluster_test.go
- helper.go
- helper_test.go
- internal/util/pool.go
- internal/util/pool_test.go
- mux.go
- mux_test.go
- pipe.go
- pipe_test.go
- sentinel.go
- sentinel_test.go
Improve throughput of the following operations by 12% to 33%.
Improve allocations of the following operations by 49% to 76%.
```
▶ benchstat old.txt new.txt
name                                      old time/op    new time/op    delta
/OneNode/128_keys_RueidisDoMulti-10         39.0µs ± 0%    39.0µs ± 0%     ~     (p=0.346 n=10+9)
/OneNode/128_keys_RueidisMGet-10            20.0µs ± 1%    19.9µs ± 1%   -0.52%  (p=0.029 n=10+10)
/OneNode/128_keys_RueidisMGetCache-10       15.6µs ± 2%    11.7µs ± 1%  -24.65%  (p=0.000 n=10+10)
/OneNode/128_keys_RueidisDoMultiCache-10    10.0µs ± 3%     7.8µs ± 1%  -21.88%  (p=0.000 n=10+10)
/Cluster/128_keys_RueidisDoMulti-10         40.8µs ± 4%    35.1µs ± 3%  -13.81%  (p=0.000 n=10+10)
/Cluster/128_keys_RueidisMGet-10            43.6µs ± 3%    38.3µs ± 5% …
```
> perf: reuse intermediate alloc

- lru.go
- lru_test.go
- pipe.go
- pipe_test.go
Improve throughput by 13% to 42%
```
▶ benchstat old.txt new.txt
name                                 old time/op    new time/op    delta
/OneNode/128_RueidisMGetCache-10       11.7µs ± 2%    10.2µs ± 0%  -13.50%  (p=0.000 n=10+8)
/OneNode/128_RueidisDoMultiCache-10    7.75µs ± 1%    4.58µs ± 1%  -40.85%  (p=0.000 n=10+9)
/Cluster/128_RueidisMGetCache-10       12.9µs ± 4%    10.9µs ± 1%  -15.36%  (p=0.000 n=10+8)
/Cluster/128_RueidisDoMultiCache-10    9.00µs ± 3%    5.22µs ± 4%  -42.07%  (p=0.000 n=10+10)
name                                 old alloc/op   new alloc/op   delta
/OneNode/128_RueidisMGetCache-10       31.0kB ± 1%    31.1kB ± 1%     ~     (p=0.754 n=10+10)
/OneNode/128_RueidisDoMultiCache-10    11.9kB ± 1%    11.8kB ± 1%   -1.31%  (p=0.000 n=10+10) …
```
> perf: use batched lru.Flights to reduce cache contentions

- mux.go
- pipe.go
- redis_test.go
- ring.go
- ring_test.go
- rueidis.go
Improve throughput of the `Do` and `DoMulti` by **15%** and **8%** when `-cpu=1`.
```
goos: linux
goarch: amd64
pkg: github.com/redis/rueidis/ben
cpu: AMD EPYC 7B12
│   old-1.txt   │              new-1.txt               │
│    sec/op     │    sec/op     vs base                │
/OneNode/128_RueidisSingle      102.39µ ±  7%   86.42µ ± 11%  -15.60% (p=0.001 n=10)
/OneNode/128_RueidisDoMulti      242.8µ ±  5%   223.1µ ±  6%   -8.11% (p=0.019 n=10)
geomean                          146.8µ         139.4µ         -5.03%
│  old-1.txt   │               new-1.txt                │
│     B/op     │     B/op      vs base                  │
/OneNode/128_RueidisSingle       243.50 ± 4%     64.00 ± 0%  -73.72% (p=0.000 n=10)
/OneNode/128_RueidisDoMulti     18.46Ki ± 0%   18.02Ki ± 0%   -2.37% (p=0.000 …
```
> perf: improve throughput of the Do and DoMulti when -cpu=1

- cluster.go
- internal/util/parallel.go
- mux.go
```
▶ benchstat old.txt new.txt
name                                 old time/op    new time/op    delta
/OneNode/128_RueidisDoMulti-10         42.0µs ± 0%    42.1µs ± 0%   +0.33%  (p=0.000 n=20+19)
/OneNode/128_RueidisDoMultiCache-10    4.24µs ± 1%    3.96µs ± 2%   -6.73%  (p=0.000 n=19+20)
/Cluster/128_RueidisDoMulti-10         28.8µs ± 4%    29.1µs ± 4%     ~     (p=0.157 n=20+20)
/Cluster/128_RueidisDoMultiCache-10    4.24µs ± 2%    4.21µs ± 3%   -0.86%  (p=0.037 n=20+20)
name                                 old alloc/op   new alloc/op   delta
/OneNode/128_RueidisDoMulti-10         18.5kB ± 0%    18.5kB ± 0%     ~     (p=0.513 n=20+19)
/OneNode/128_RueidisDoMultiCache-10    11.8kB ± 1%    11.5kB ± 0%   -2.84%  (p=0.000 n=20+20)
/Cluster/128_RueidisDoMulti-10         19.4kB ± 1% …
```
> perf: reduce allocations of DoMultiCache

- resp.go
Before:
```
goos: darwin
goarch: arm64
pkg: rueidis-benchmark/single
Benchmark
Benchmark-10    	  372879	      3199 ns/op	       4 B/op	       1 allocs/op
PASS
```
After:
```
goos: darwin
goarch: arm64
pkg: rueidis-benchmark/single
Benchmark
Benchmark-10    	  380086	      3180 ns/op	       0 B/op	       0 allocs/op
PASS
```
```go
package main
import (
"context"
"strings"
"testing"
"github.com/redis/rueidis"
)
func Benchmark(b *testing.B) {
client, err := rueidis.NewClient(rueidis.ClientOption{
InitAddress:       []string{"127.0.0.1:6379"},
PipelineMultiplex: -1,
})
panic(err)
}
key := strings.Repeat("k", 16)
val := strings.Repeat("v", 64)
b.ReportAllocs()
b.ResetTimer()
b.RunParallel(func(pb *testing.PB) {
for pb.Next() {
if err := client.Do(context.Background(), …
```
> perf: no allocations for redis OK responses

- mux_test.go
- pipe.go
- pipe_test.go
- rueidis_test.go
https://github.com/redis/go-redis/issues/2654#issuecomment-1651073598
> feat: always using Redis 7.2 CLIENT SETINFO command to set library name

- internal/cmds/builder.go
Related to https://github.com/redis/rueidis/issues/312
Go 1.21 is not yet released. We can use the new `clear` function once it is released.
> perf: clear builder slices eagerly to help GC

- cluster.go
- cluster_test.go
Maybe related to https://github.com/redis/rueidis/discussions/320
> fix: handle MOVED errors for non-readonly commands in DoMulti

- helper.go
- internal/cmds/builder.go
- internal/cmds/builder_test.go
Using the same benchmark of https://github.com/redis/rueidis/pull/287
```
▶ benchstat old.txt new.txt
goos: darwin
goarch: arm64
pkg: rueidis-benchmark/sep
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
/OneNode/128_RueidisDoMulti-10        41.34µ ± 0%   41.49µ ± 0%  +0.36% (p=0.005 n=10)
/OneNode/128_RueidisMGet-10           21.53µ ± 0%   20.86µ ± 0%  -3.10% (p=0.000 n=10)
/OneNode/128_RueidisMGetCache-10      10.81µ ± 1%   10.19µ ± 1%  -5.75% (p=0.000 n=10)
/OneNode/128_RueidisDoMultiCache-10   4.097µ ± 1%   4.078µ ± 1%       ~ (p=0.137 n=10)
/Cluster/128_RueidisDoMulti-10        30.50µ ± 4%   29.52µ ± 3%       ~ (p=0.075 n=10)
/Cluster/128_RueidisMGet-10           34.63µ ± 4%   33.94µ ± 1%       ~ (p=0.123 n=10) …
```
> perf: recycle intermediate allocations in MGet/MSet helpers

- om/json.go
Fix https://github.com/redis/rueidis/issues/338
> fix: always use the . legacy root syntax in om.JSONRepository

- message.go
- message_test.go
> Feat: Human readable results

- url.go
- url_test.go
This change sets the TLS server name to the url host and it also sets the minimum TLS version to use. This keeps the compatibility with go-redis url parsing and how it handles TLS configs
I added a unit test to assert that the server name is set correctly in the TLS config. The existing unit test on line 12 should cover the fact that 'redis://' urls are not affected by this change
> Add servername and min tls version to tls config

- pipe.go
- pipe_test.go
- rueidis.go
We are developing an implementation of short-lived token authentication for Redis which requires that the password associated with the Redis authentication change as new tokens are generated to replace expired tokens. I'm proposing support for this within Rueidis in the form of configurable auth credential function which allows for setting a new password on each dial as needed.
> Add option for an AUTH credential function

- internal/cmds/cmds.go
- mux_test.go
- pipe.go
- pipe_test.go
- ring_test.go
- rueidis_test.go
This PR resolves #377.
From the suggestion in the documentation in Redis [QUIT (deprecated)](https://redis.io/commands/quit/)
> Note: Clients should not use this command. Instead,
> clients should simply close the connection when they're not used anymore.
> Terminating a connection on the client side is preferable,
> as it eliminates TIME_WAIT lingering sockets on the server side.
We should close the connection by ourselves,
so I changed to last command from QUIT to PING to wait for other pending commands to be completed.
> feat: avoid using QUIT command

- pipe.go
We check if one or multi has block command, if true, then there's no need to sleep.
> fix: ignore MaxFlushDelay for blocking commands

- rueidiscompat/adapter.go
- rueidiscompat/adapter_test.go
- rueidiscompat/hscan_test.go
- rueidiscompat/structmap.go
Easy way to implement support for pointers to primitives at the `Scan()` method. Uses built-in decoders by just passing the kind of the element of the pointer to the decoders map.
> feat: support for pointers to primitives in Scan() and HSet()

- docker-compose.yml
- hack/cmds/commands_gears2.json
- internal/cmds/builder.go
- internal/cmds/gen_triggers_and_functions.go
- rueidiscompat/adapter.go
- rueidiscompat/adapter_test.go
- rueidiscompat/command.go
This PR adds `GearsCmdable` to our `go-redis` API adapter, and copied the tests from `go-redis` to make sure that it's compatible.
> feat: Add `GearsCmdable` to `go-redis` API adapter

- binary_test.go
Running into some issues parsing vector embeddings in a project. They vectors are normalized and was wondering if that was the issue after looking at the tests for the function. Looks like it is not but adding these tests for better coverage.
> Add Normalized Vector Tests for `TestVectorString32`/`64`

- cluster.go
- cluster_test.go
- internal/cmds/cmds.go
- rueidis.go
- rueidis_test.go
previous discussion: https://github.com/redis/rueidis/discussions/400
add read-write splitting when cluster mode
> feat: read-write splitting

- url.go
- url_test.go
A simple fix for #424. And a simple test as well.
> fix: rueidis.ParseURL() cannot parse unix address

- message.go
- rueidiscompat/adapter.go
- rueidiscompat/adapter_test.go
- rueidiscompat/command.go
This PR implemented adapter for `go-redis` `TimeseriesCmdable`.
> Feat: Align `go-redis` `TimeseriesCmdable`

- url.go
- url_test.go
If the error is ignored, there will be a nil pinter dereference panic when accessing `u.Scheme`.
> fix: do not ignore error of `url.Parse`

- mux.go
- redis_test.go
This issue is introduced by https://github.com/redis/rueidis/pull/418 where it changes the previous PipelineMultiplex behavior for cluster clients and causes this bug when casting a cluster client to a single client.
> fix: random nil dereference caused by non-zero PipelineMultiplex

- rueidisotel/metrics.go
- rueidisotel/trace.go
**First commit**: it's good to avoid mutable public fields because they encourage poor user behavior. It's possible to configure the histogram buckets via options, no need to make the default value mutable.
**Second commit**: it's better to fail early if OTEL library returned an error rather than discard an error, store `nil` in the field and then panic with NPE later. There will be no way to find out why the field was `nil` because the error was discarded. Also, it'd be better if `WithClient()` just returned an error.
**Third commit**: `Second()` does something weird instead of just division. It loses precision that way. OpenTelementry libraries just use division, e.g. https://github.com/open-telemetry/opentelemetry-go-contrib/blob/8e44cea6d4fe181343500b6cb680bd501b3d24aa/instrumentation/ …
> OTEL tweaks

- rueidis.go
If we use `ClientOption.PipelineMultiplex` in the wrong way (too big), we will get a panic inside rueidis:
https://go.dev/play/p/QE8VYHE6hJX
```
package main
func foo(v int) int {
return 1 << v
}
func main() {
println(foo(0), foo(2), foo(50), foo(70), foo(100), foo(200))
}
>> 1 4 1125899906842624 0 0 0
```
In this case, we will get [zero for multiplex value](https://github.com/redis/rueidis/blob/a85dd76338d31ff6e92e55d698dd536e5ea6f10a/mux.go#L97) and zero-sized `wire`, `mu`, `sc` slices. Which will lead to panic [here](https://github.com/redis/rueidis/blob/a85dd76338d31ff6e92e55d698dd536e5ea6f10a/mux.go#L142) for example.
```
goroutine 59 [running]:
github.com/redis/rueidis.(*mux)._pipe(0x0?, 0x0?)
/home/X/go/pkg/mod/github.com/redis/rueidis@v1.0.25/mux.go:142 +0x71e …
```
> Check for too big option.PipelineMultiplex value

- internal/cmds/cmds.go
- internal/cmds/cmds_test.go
Resolves https://github.com/redis/rueidis/issues/440
> feat: SetSlot to override the calculated key slot of a command

- hack/cmds/gen.go
- internal/cmds/gen_stream.go
- internal/cmds/gen_timeseries.go
closes #445 
I don't know well about timeseries but I think the same fix should be applied.
> fix wrong block tag setting

- rueidislock/lock.go
- rueidislock/lock_test.go
fixes #457 
There is a rare chance that when receiving `bulking invalidation` and all peers are aborted, the following line https://github.com/redis/rueidis/blob/33e9233955925a4e66fe2d8613443c4ca95ef5df/rueidislock/lock.go#L324 blocks indefinitely and causes deadlock reported in the #457.
This PR removes the unnecessary notification to the `g.ch` from the `bulking invalidation` and makes the mutex never be blocked.
> fix: rueidislock deadlock caused by the absence of peers

- README.md
- client.go
- client_test.go
- cluster.go
- cluster_test.go
- lua_test.go
- mock/client.go
- mock/client_test.go
- mock/result.go
- mock/result_test.go
- mux.go
- mux_test.go
- pipe.go
- pipe_test.go
- redis_test.go
- resp.go
- resp_test.go
- rueidis.go
- rueidishook/hook.go
- rueidishook/hook_test.go
- rueidisotel/trace.go
- rueidisotel/trace_test.go
- sentinel.go
- sentinel_test.go
This is a draft of #450.
Initial benchmark result with redjet v0.5.0:
```
▶ go test -bench . -benchtime=3s
goos: darwin
goarch: arm64
pkg: rueidis-benchmark/redjet
Benchmark/single/rueidis/payload1B-10         	  697377	      5117 ns/op	       0 B/op	       0 allocs/op
Benchmark/single/rueidis/payload1K-10         	  626092	      5241 ns/op	       0 B/op	       0 allocs/op
Benchmark/single/rueidis/payload1M-10         	   19602	    181655 ns/op	       1 B/op	       0 allocs/op
Benchmark/single/redjet/payload1B-10          	  657787	      5283 ns/op	     256 B/op	       4 allocs/op
Benchmark/single/redjet/payload1K-10          	  632977	      5408 ns/op	     256 B/op	       4 allocs/op
Benchmark/single/redjet/payload1M-10          	   17818	    201544 ns/op	     291 B/op	       5 allocs/op …
```
> feat: streaming read with DoStream() and DoMultiStream()

- rueidis.go
previous disccusion: https://github.com/redis/rueidis/discussions/468
Add comments that `ConnWriteTimeout` can be request timeout to commands
> doc: add comments to `ConnWriteTimeout` as a request timeout

- rueidisotel/metrics.go
- rueidisotel/trace.go
> fix: respect rueidisotel.MetricAttrs options, and avoid copy them repeatedly

- rueidisotel/metrics.go
> fix: panic rueidisotel without MetricAttrs and TraceAttrs

- .circleci/config.yml
The tests of subpackages, such as `rueidisotel` and `rueidiscompat`, were skipped on the CI since we introduced separated `go.mod` files for them. This PR fixes that.
> ci: run tests of sub go.mod on circleci

- rueidiscompat/adapter.go
- rueidiscompat/command.go
This PR add `baseCmd` to `go-redis` adaptor commands.
Note that there are some Commands that can't use `baseCmd` due to incompatible method
signature for `(*Command).SetVal`, `(*Command).Val`, `(*Command).Result`.
e.g. `KeyValuesCmd`, `ZSliceWithKeyCmd`, `XAutoClaimCmd`, `XAutoClaimJustIDCmd`.
> Refactor: add baseCmd to go-redis adaptor commands

- README.md
Resolves #435.
- I restructured the document so that client instantiation is placed at the top. In the old version, the section was at the very bottom, which was inconvenient for a new reader.
- I also improved the URL build options text by looking at `rueidis/url.go`
> feat: improve client instantiation examples

- rueidiscompat/command_test.go
Add some unit tests in command.go
https://github.com/redis/rueidis/issues/487
> Improve unit test coverage in command.go

- helper.go
- helper_test.go
added a helper function DecodeSliceOfJSON to struct scan a redis result.
code provided in https://github.com/redis/rueidis/issues/521#issuecomment-2029762737 did not work so I changed a little.
close #521
> feat: Add a helper generic function DecodeSliceOfJSON

- rueidisotel/trace.go
- rueidisotel/trace_test.go
Add tracer option to add the whole command's statement to db.statement attribute.
Need this for integration with APM and couldn't find another way that doesn't involve copying a lot of code from `otelClient`'s implementation.
I mostly use non-multi operations and they seem a bit more complex and opinionated so I didn't implement it on my own.
> Add WithDBStatement to add db.statement attribute to rueidisotel

- rueidisprob/README.md
- rueidisprob/bloomfilter.go
- rueidisprob/countingbloomfilter.go
- rueidisprob/countingbloomfilter_test.go
Previous Discussion: https://github.com/redis/rueidis/discussions/510
There are 2 different points from origin design.
1. `Count` returns all inserted items. not distinct items.
2. `RemoveMulti` deduplicate keys. count in Counting Bloom Filter can't be negative. because of these nature, `RemoveMulti` operation can be complicated and performance can be bad. so add constraints to avoid difficulties.
> feat: add counting bloom filter

- lru.go
> fix: rare nil dereferences in lru (ele.Value.(*cacheEntry))

- message.go
- message_test.go
> fix: ipv6 handling in MOVED and ASK messages of cluster mode

- rueidisprob/bloomfilter.go
- rueidisprob/countingbloomfilter.go
fix: https://github.com/redis/rueidis/issues/513
returning uint64 to avoid incorrect conversion
> fix: incorrect conversion

- rueidislock/lock.go
This improves the responsiveness of locks.
> perf: reconstruct client-side caching in rueidislock after extending key validities

- rueidiscompat/command.go
- rueidiscompat/command_test.go
Add tests for String() method coverage
Add tests for formatMs method
> Add Tests for rueidis compat

- message.go
- message_test.go
This is to address #366 
This is in draft state with some idea I understood from the current proposal thread.
We can discuss and decide on what specifically we want to do here, and how much of it has to stay backwards compatible and in what all way and whether we want to introduce some breaking major changes too.
@rueian Let's continue the discussion further on this
> feat: Panic -> Error migration

- mux.go
- pipe.go
- pipe_test.go
https://github.com/redis/rueidis/issues/156#issuecomment-2167410921 follow up.
> fix: remove unnecessary busy loop during shutdown

- client.go
- cluster.go
- helper.go
- helper_test.go
- sentinel.go
- sentinel_test.go
> feat: fallback MGetCache to MGet

- cluster.go
- cluster_test.go
The endpoint is just a DNS alias to any nodes. There is no need for a special treatment.
> fix: remove unnecessary aws configuration endpoint specialization

- client.go
- client_test.go
- cluster.go
- cluster_test.go
- rueidis.go
Relates #586 
This PR contains changes to avoid panicking with `DedicatedClient should not be used after recycled`, and return an error (specifically, `ErrClosing`) instead.
Please take a look. The thing I personally not sure whether it's semantically correct to use `ErrClosing` in these places. At first glance seems logical, but probably will require adjustments. Also, #586 mentions only panic for `Do` call, but I guess it should be extrapolated to all methods to fully eliminate panic.
> Avoid panic when using dedicated client after being recycled, return an error instead

- client.go
Hey, 
This fixes #591
Let me know if i have to add anything else.
> fix: jsonRespository.DoCache does not hang when redisjson  module is not installed

- rueidiscompat/adapter.go
- rueidiscompat/pubsub.go
- rueidiscompat/pubsub_test.go
Ref: https://github.com/orgs/valkey-io/discussions/797
> feat: add PubSub to rueidiscompat

- rueidisprob/bloomfilter.go
- rueidisprob/bloomfilter_test.go
- rueidisprob/countingbloomfilter.go
- rueidisprob/countingbloomfilter_test.go
I got error, when `redis.call` parameters are too large.
```
user_script:15: too many results to unpack script: 73a336266d816e4bcf60d6cf47daafcad23ad693, on @user_script:15
```
`LUAI_MAXCSTACK` in luaconf.h limits stack slots. script can run very long, but it should be avoided by user not rueidisprob.
> fix: too large arguments

- rueidisprob/bloomfilter.go
- rueidisprob/bloomfilter_test.go
- rueidisprob/countingbloomfilter_test.go
[Discussion](https://github.com/redis/rueidis/discussions/597)
As we discussed before, supporting replica when using bloom filter.
> feat: add enable read operation

- rueidislock/lock.go
- rueidislock/lock_test.go
Closes #602 
This PR keeps using the same event watcher of client-side caching during the retries of `rueidislock.WithContext` and watches the event for retrying.
Previously, there was a race that could lead to the removal of the watcher thus causing busy retries and missing events.
> Fix rueidislock highload

- rueidisotel/metrics.go
- rueidisotel/trace.go
Please see individual commits.
See also:
- Why `metric.WithAttributeSet()`: https://github.com/open-telemetry/opentelemetry-go/blob/metric/v1.28.0/metric/instrument.go#L349-L368.
- Why reuse those slices: https://go.dev/ref/spec#Passing_arguments_to_..._parameters
> OpenTelemetry client optimizations

- .github/workflows/build.yml
- internal/cmds/iter.go
- internal/cmds/iter_test.go
closes #355
I added iter.Seq2 support for `HSET`, `HMSET`, `XADD` which have `FieldValue()` method.
We must support `< go 1.23`, so we must split file to other files.
It's hard to support auto generation because current implementation does not support code splitting.
So I hand-written the implementation.
When go version in `go.mod` is `go 1.23`, I think we can support auto generation by adding flags to `*.json` and its structs.
I named `FieldValues`, but this is maybe not good to support auto generation in the future because we must consider plural form correctly.
Is `FieldValueSeq` better?
> Support iter.Seq2 for *FieldValue

- pipe.go
- pipe_test.go
- rueidis.go
This pull request addresses #620 and adds a `DisableClientSetInfo` constant to be used for the `ClientSetInfo` field of `ClientOption`. 
When this constant is used, the `CLIENT SETINFO` command and relevant paths are skipped during new connection initialization, in order to be compatible with older versions of Redis (<7.2) that do not have the `CLIENT SETINFO` command.
- Add DisableClientSetInfo path and test
> Add option to disable making `CLIENT SETINFO` command on initialization

- mux.go
- mux_test.go
- rueidis.go
Related to https://github.com/redis/rueidis/issues/626
Automatically switch to use dedicated connections for `DoMulti()` with 2000+ commands by default to avoid head-of-line blocking. The threshold can be adjusted with the new `BlockingPipeline` option.
The switch is done at the `mux` level so that users don't need to use `Dedicated` manually and no more `cross slot` errors.
> perf: use dedicated connections for DoMulti() with 2000+ commands by default

- cluster.go
- cluster_test.go
- rueidis.go
discussion: https://github.com/redis/rueidis/discussions/637
> feat: add clutser topology awareness

- client.go
- cluster.go
- sentinel.go
follow up: https://github.com/redis/rueidis/pull/643
If above PR merged, i merge main branch then cleaned it up.
clusterClient:
singleClient:
dedicatedSingleClient:
dedicatedClusterClient:
sentinelClient:
> Also, can retryHandler be just a struct instead of a pointer to struct?
@rueian 
I don't understand the meaning. you want to change pointer receiver?
> [follow-up] perf: optimize struct layout

- pipe.go
- rueidis.go
We found that turning on Nagle's algorithm (`DisableTCPNoDelay=true`) may improve performance depending on the network condition and workloads, especially when all your requests are small and your network interfaces are relatively slow.
Benchmark results on 2 GCP n2-highcpu-2 machines (client and redis server):
PipelineMultiplex=-1 (1 connection):
PipelineMultiplex=1 (2 connections):
PipelineMultiplex=2 (4 connections):
> feat: add DisableTCPNoDelay

- internal/cmds/iter.go
- internal/cmds/iter_test.go
https://github.com/redis/rueidis/issues/644
> Support Go 1.23 iterators for the ZADD command 

- om/hash.go
- om/hash_test.go
- om/json.go
- om/json_test.go
- om/repo.go
Signed-off-by: Vatsal <vatsal.v.anand@gmail.com>
Closes #632.
> Add FT.ALTER in OM JSON and Hash repo

- singleflight.go
This moves the sleep of up to `threshold` out of the caller's request path. This allows callers to use `LazyDo` without sleeping for up to `threshold` when called in succession.
This allows requests to connections that fail to return immediately instead of waiting for a second when they are selected to lazily perform the topology refresh.
Discussed here: https://github.com/redis/rueidis/issues/658
> Move sleep into goroutine in `LazyDo`

- cluster.go
- cluster_test.go
Previously, rueidis may pick a failed node as the primary node of a shard, especially if the failed node doesn't come back online. This PR skips those failed nodes and only picks nodes labeled as healthy as primaries.
Related to https://github.com/redis/rueidis/issues/658 and https://github.com/redis/rueidis/issues/384#issuecomment-2452676261
> fix: do not pick failed cluster nodes while refreshing topology

- client.go
- client_test.go
- cluster.go
- cluster_test.go
- message.go
- sentinel.go
- sentinel_test.go
When a Redis node is loading data (e.g. after restart), it responds with LOADING errors. This makes the client more resilient during Redis node restarts and initial data loading phases.
Close: #656
> feat: improve handling of LOADING response

- cluster.go
- cluster_test.go
Ref:
https://github.com/redis/rueidis/issues/384#issuecomment-2463031313
https://github.com/redis/redis/pull/13422
https://github.com/valkey-io/valkey/issues/784
> fix: refresh cluster topology with `CLUSTER SLOTS` instead of `CLUSTER SHARDS` for clusters which version < 8 due to the server bug.

- rueidislimiter/README.md
- rueidislimiter/go.mod
- rueidislimiter/go.sum
- rueidislimiter/limiter.go
- rueidislimiter/limiter_test.go
The module is inspired by [GitHub's approach](https://github.blog/engineering/infrastructure/how-we-scaled-github-api-sharded-replicated-rate-limiter-redis/) to scaling rate limiting with Redis to support high-traffic APIs in a distributed system.
- **Token Bucket Rate Limiting**: Implements a token bucket algorithm to limit the number of requests a client can make within a specified time window.
- **Customizable Configuration**: Allows setting custom limits and time windows for each rate limiter instance.
- **Distributed Consistency**: Uses Redis as a backend to ensure consistency and persistence of rate limits across distributed systems.
- **Reset Information**: Provides helpful information about when the next allowed request can occur `RetryAt`.
> Add rueidislimiter Module for Distributed Rate Limiting

- pipe.go
- pipe_test.go
When returning a dedicated connection to the pool, we try to clear its pubsub subscriptions by sending a UNSUBSCRIBE request. But if the connection is currently in blocking, we will never get UNSUBSCRIBE response. We should just close the connection instead.
> fix: close connections that are still blocked while recycling them to pools

- mux.go
- mux_test.go
Route blocking commands to the `dpool` where connections can go pipelining and respect manual context cancellation.
Previously, blocking commands are route to the `spool` where pipelining is always disabled.
> chore: use dpool for blocking commands to be able to respect more on ctx

- rueidislock/lock.go
- rueidislock/lock_test.go
1. Previously when we consumed CSC notifications from the watched locks, we might skip the registration because the internal `gate` was still holed. This PR doesn't skip the registration anymore.
2. We respect the custom deadline passed in the context if it is shorter than key validity.
> Rueidislock CSC re-register

- pipe.go
- pipe_test.go
- redis_test.go
Resolves https://github.com/redis/rueidis/issues/671 due to the historical assumption that it is no longer held.
> fix: hide os.ErrDeadlineExceeded with context.DeadlineExceeded only when ConnWriteTimeout is shorter

- rueidiscompat/command.go
This PR fixed incorrect conversion between int and int64 at `FTSearchResult.Result`, simply made `Result` an `int` type to avoid conversion.
> fix incorrect conversion between int and int64

- mux.go
- pipe_test.go
- pool.go
- pool_test.go
- rueidis.go
Approach for [#651 ](https://github.com/redis/rueidis/issues/651)
> Added options for configuring removal of idle connections

- rueidislimiter/limit.go
- rueidislimiter/limiter.go
- rueidislimiter/limiter_test.go
Currently it's not possible to use instance of RateLimiter and share it with different use cases.
> FEATURE rueidislimiter: Introduce RateLimitOption to RateLimiterClient

- cluster.go
We only avoid unhealthy masters currently. This PR can provide more stable replica reads to users who are using `SendToReplicas` and `ReplicaOnly`.
> fix: avoid picking unhealthy replicas

- cluster.go
- cluster_test.go
Resolves #635
What's changed:
In `(c *clusterClient) _refresh()`, when values in `ClientOption.InitAddress` is not in the return value of `getClusterSlots`, it should be hidden.
> feat: Hide InitAddress when connecting to a redis cluster using NewClient()

- hack/cmds/gen.go
- internal/cmds/cmds.go
- internal/cmds/cmds_test.go
- internal/cmds/gen_pubsub.go
- pipe.go
- pipe_test.go
Fixes https://github.com/redis/rueidis/issues/690
In the TCP dumps provided by the issuer, we found the following traces during slot migration:
```
1. client -> [SUNSUBSCRIBE channel1] -> server
2. server -> [sunsubscribe channel1] -> client
3. client -> [HGET key field] --------> server
4. server -> [MOVED slot address] ----> client
5. server -> [True HGET response] ----> client
```
In the above sequence, (2) was the proactive `sunsubscribe` message sent by the server due to slot migration, and the message was wrongly delivered to the (1) `SUNSUBSCRIBE` request sent by the user. The true response to the (1) should be (4), the `MOVED`.
The wrong delivery of (2) caused the pipeline out-of-sync. The (4) `MOVED` was also wrongly delivered to (3), the `HGET` request. Then finally the (5), the …
> fix: protocol out of sync when mixing sunsubscribe requests and slot migrations

- cluster.go
- cluster_test.go
- internal/cmds/cmds.go
Fixes #694
The situation happened when a cluster node got promoted to be the primary and the client followed a `MOVED` redirection but still think the node as a replica. Then the client set the connection to the `rslots` which was not yet initialized. This PR changes two things:
1. Remove the `connrole.replica` field because, in the future, a node can have mixed roles. https://github.com/valkey-io/valkey/issues/1372
2. Trust the `MOVED` redirection. ie. It always points to the primary of the slot so the client should set the connection to `pslots` directly.
Hi @proost, could you help review this?
> fix: panic on cluster redirection to a node with stale role

- cluster.go
- cluster_test.go
try fix #696
add two mock testcase for `ClusterClient.DoMulti` on error MOVED / ASK
Also tested in our real test environment multiple times and it worked perfectly.
> fix: DoMulti should retry on MOVED / ASK

- cluster.go
I found that last slot of command and toReplica are useless. So remove it.
> refactor: clean up unused return values

- cluster.go
We removed one optimization for DoMulti in a cluster client previously: https://github.com/redis/rueidis/issues/696.
Now, we make the normal path use fewer goroutines for compensation.
> perf: reduce goroutines used by DoMulti/DoMultiCache in a cluster client

- message.go
- message_test.go
Discussion: https://github.com/redis/rueidis/discussions/455#discussioncomment-11419197
Other third-party cache libraries often only accept []byte as input.
This PR adds `CacheMarshal` and `CacheUnmarshalView` to convert a `RedisMessage` to []byte and convert it back.
We don't use standard `Marshal` and `Unmarshal` interfaces because of performance concerns.
> feat: CacheMarshal and CacheUnmarshalView for third party cache libraries

- cluster.go
try fix #703 
ref: 
> https://redis.io/docs/latest/commands/asking/
> If an -ASK redirect is received during a transaction, only one ASKING command needs to be sent to the target node before sending the complete transaction to the target node.
> fix: asking should send right before multi

- cluster.go
> fix: do not recycle the intermediate commands slice of cluster DoMulti when network errors

- rueidisaside/README.md
- rueidisaside/typed_aside.go
- rueidisaside/typed_aside_test.go
This PR introduces the `TypedCacheAsideClient` to the rueidisaside package, enhancing its functionality by supporting typed values instead of being limited to strings. The implementation includes serialization and deserialization capabilities, allowing for more flexible and type-safe caching of various data structures such as JSON objects, integers, lists, etc.
This PR addresses the discussion and enhancements proposed in [Issue #716](https://github.com/redis/rueidis/issues/716).
- TypedCacheAsideClient Implementation:
- Added a new generic interface `TypedCacheAsideClient[T any]` that allows caching and retrieving values of any specified type.
- Implemented serialization and deserialization functions to handle the conversion between typed values and their string representations in Redis. …
> feat: Add typed cache-aside client implementation and tests

- pipe.go
- pipe_test.go
Fix #718 
Treat `LOADING server is loading the dataset in memory` error from redis server as a `PONG` reply.
> fix: ignore LOADING error to prevent out of sync order message

- rueidisprob/README.md
- rueidisprob/slidingbloomfilter.go
- rueidisprob/slidingbloomfilter_test.go
- rueidisprob/synp.go
- Contains two Bloom filters: current and next
- Elements are added to both filters. 
- At the half of the window the filters are rotated current is dropped, next becomes current
this is done in Redis to warranty an atomic operation.
1. Key structure:
- '{name}' is the current filter.
-  '{name:c}' is the current counter.
- '{name}:n' is the next filter
- '{name}:nc' is the next counter.
- '{name}:lr' is the last rotation lock to avoid multiples rotations in a given period
2. Scripts:
- Add: Sets bits in the current and next filters.
- Exists: Checks just bits in the current filter.
- Rotate: swaps the next filter with the current one, creating a new next filter.
3. Rotation Coordination:
- Clients track rotation timing locally and just trigger the rotation that will only be executed if …
> feat: implement Sliding Window Bloom Filter

- rueidisprob/bloomfilter.go
- rueidisprob/countingbloomfilter.go
- rueidisprob/countingbloomfilter_test.go
- rueidisprob/slidingbloomfilter.go
Optimizes memory allocations in bloom filter operations, resulting in:
- 99.13% fewer allocations in BloomFilter operations
- 98.54% fewer allocations in CountingBloomFilter operations
- 21.72% less memory usage in BloomFilter operations
- 17.25% less memory usage in CountingBloomFilter operations
- 2.41% faster BloomFilter operations
- 2.48% faster CountingBloomFilter operations
```
goos: linux
goarch: amd64
pkg: github.com/redis/rueidis/rueidisprob
cpu: AMD Ryzen 7 7840HS with Radeon 780M Graphics   
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
BloomFilterAddMultiBigSize-16       355.3µ ± 4%   348.8µ ± 1%  -1.84% (p=0.012 n=20)
BloomFilterAddMultiLowRate-16       642.8µ ± 6%   625.5µ ± 1%  -2.69% (p=0.000 n=20) …
```
> perf(rueidisprob): reduce allocations in bloom filter operations

- client_test.go
- cluster.go
- cluster_test.go
- mux.go
- mux_test.go
- pipe.go
- pipe_test.go
- rueidis.go
previous discussion: https://github.com/redis/rueidis/discussions/710
> feat: add AZ to replica info

- rueidiscompat/adapter.go
- rueidiscompat/pipeline.go
> feat: add ACLSetUser to rueidiscompat

- rueidiscompat/adapter.go
- rueidiscompat/pipeline.go
> feat: add ACLCat to rueidiscompat

- rueidiscompat/adapter.go
- rueidiscompat/pipeline.go
As https://github.com/redis/rueidis/issues/743 mentioned, add an ACLCatArgs method to provide the same interface with go-redis.
This function requires `function ACLCat` to be done first, so I created an interface first.
> feat: Add ACLCatArgs to rueidiscompat

- pool.go
- redis_test.go
If there is no free wire in the pool, as len(p.list) == 0, it blocks the whole pool until make wire returns. 
The process of making new wire usually take several millionseconds under my environment. But if serveral tasks acquire new wires in that short period concurrently, some tasks may need to wait tens of millionseconds which brings down performance dramatically.
> Fix: pool acquire allowing concurrently make new wire instead of waiting in line

- rueidiscompat/adapter.go
- rueidiscompat/command.go
- rueidiscompat/pipeline.go
- Implemented FunctionStats in rueidiscompat to enhance functionality. 
- Ensured compatibility with existing code and followed project conventions.
- Fixes #751
> Add FunctionStats to rueidiscompat

- README.md
- internal/cmds/cmds.go
- mux.go
- mux_test.go
- redis_test.go
A solution to issue #771 
```go
client, err := NewClient(ClientOption{
InitAddress:       []string{"127.0.0.1:6379"},
// other options
DisableAutoPipelining:  true,  // change default action to use pool 
})
cmd := client.B().Get().Key(key).Build().ToPipe()   // assign this command to auto pipeline manually
client.Do(ctx, cmd)
```
> add feature to cmd, give a choice to change execution from spool to auto pipeline

- mock/result.go
- pipe.go
Changes error from `atomic.Value` to `Atomic.pointer`
Fixes #776
> enhancement atomic_pointer

- client.go
- client_test.go
- cluster.go
- cluster_test.go
- lua_test.go
- mock/client.go
- rueidis.go
- rueidiscompat/tx.go
- rueidishook/hook.go
- rueidisotel/trace.go
- sentinel.go
- sentinel_test.go
Previously, Centrifugo required explicit Redis Cluster configuration because the Centrifuge library generates keys differently in cluster mode (using hash tags). However, this approach is inconvenient because cloud providers typically provide a Redis URL (e.g., `redis://...`) without explicitly indicating whether it is a standalone Redis or a Redis Cluster. This prevents users from simply reusing the endpoint when starting Centrifugo.
```golang
type ClientMode string
const (
ClientModeCluster    ClientMode = "cluster"
ClientModeSentinel   ClientMode = "sentinel"
ClientModeStandalone ClientMode = "standalone"
)
type Client interface {
...
Mode() ClientMode
}
```
Closes #790
> feat: Add `Mode()` Method to `rueidis.Client` for Detecting Client Mode

- rueidislimiter/go.mod
- rueidislimiter/go.sum
- rueidislimiter/limiter.go
- rueidislimiter/limiter_test.go
- rueidislimiter/syncp.go
```
goos: linux
goarch: amd64
pkg: github.com/redis/rueidis/rueidislimiter
cpu: AMD Ryzen 7 7840HS with Radeon 780M Graphics   
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
AllowN-16   872.9n ± 1%   787.0n ± 0%  -9.84% (p=0.000 n=20)
│  old.txt   │              new.txt               │
│    B/op    │    B/op     vs base                │
AllowN-16   440.0 ± 0%   368.0 ± 0%  -16.36% (p=0.000 n=20)
│   old.txt   │              new.txt               │
│  allocs/op  │ allocs/op   vs base                │
AllowN-16   12.000 ± 0%   8.000 ± 0%  -33.33% (p=0.000 n=20)
```
```
go test -coverprofile=coverage.out && go tool cover -func=coverage.out
PASS
coverage: 100.0% of statements
ok      github.com/redis/rueidis/rueidislimiter 0.004s …
```
> perf: reduce allocations in rueidislimiter

- .github/workflows/build.yml
- rueidisaside/go.mod
- rueidisaside/go.sum
- rueidislimiter/go.mod
Adding CI validation to prevent future accidental module deletions
Closes #796
> fix: restore rueidisaside go.mod and add module validation

- client_test.go
- cluster.go
- internal/cmds/cmds.go
- internal/cmds/cmds_test.go
- mux.go
- mux_test.go
- pipe.go
- pipe_test.go
closes https://github.com/redis/rueidis/issues/799
> fix: don't send CLIENT CACHING YES in BCAST and OPTOUT mode

- mock/result.go
- pipe.go
> Replace sync.Once with int32 in pipe

- cache.go
- cache_test.go
- client_test.go
- cluster.go
- cluster_test.go
- helper_test.go
- lru.go
- lru_test.go
- lua_test.go
- message.go
- message_test.go
- mock/result.go
- mux_test.go
- pipe.go
- pipe_test.go
- redis_test.go
- resp.go
- resp_test.go
- rueidis_test.go
- sentinel.go
- sentinel_test.go
Replace the fields in `RedisMessage` with `*byte` and `*RedisMessage` in conjunction with integer to save the size of struct.
Use `unsafe.String()` or `unsafe.Slice()` to recover back to the original `string` or `[]RedisMessage` accordingly.
related issue: https://github.com/redis/rueidis/issues/789
> feat: reduce size of redis message

- pipe.go
- pipe_test.go
@rueian Please take a look at this
solves #807
> feat: merge waits and recvs to wrCounter

- rueidis.go
- rueidis_test.go
- standalone.go
- standalone_test.go
Introduce a new `StandaloneOption` mainly for the reader endpoint provided by cloud vendors:
```go
c, err := rueidis.NewClient(rueidis.ClientOption{
InitAddress: []string{"writer endpoing"},
Standalone: rueidis.StandaloneOption{
ReplicaAddress: []string{"reader endpoint"},
},
SendToReplicas: func(cmd rueidis.Completed) bool {
return cmd.IsReadOnly()
},
})
```
> feat: allow standalone client to have replicas

- hack/cmds/commands.json
- internal/cmds/gen_connection.go
According to the redis documentation, the CLIENT KILL command has the following syntax:
`
CLIENT KILL <ip:port | <[ID client-id] | [TYPE <NORMAL | MASTER |
SLAVE | REPLICA | PUBSUB>] | [USER username] | [ADDR ip:port] |
[LADDR ip:port] | [SKIPME <YES | NO>] | [MAXAGE maxage]
[[ID client-id] | [TYPE <NORMAL | MASTER | SLAVE | REPLICA |
PUBSUB>] | [USER username] | [ADDR ip:port] | [LADDR ip:port] |
[SKIPME <YES | NO>] | [MAXAGE maxage] ...]>>
`
Currently in the builder in the function `.Maxage(maxage int64)` the keyword "MAXAGE" is not formed.
Because of this, redis returns the error "ERR syntax error" in the new format of the KILL command and the error "ERR No such client" in the old format.
> fix: syntax of the MAXAGE option in the CLIENT KILL command is aligned with the redis docs

- rueidisotel/README.md
- rueidisotel/metrics.go
- rueidisotel/metrics_test.go
- rueidisotel/trace.go
- rueidisotel/trace_test.go
We would find it useful to track aggregated metrics outside of the spans emitted.
> feat: emit metrics for command duration and errors

- lua.go
- lua_test.go
Hello,
First of all, sorry for bringing some mess to rueidis 🙏  But generally this change can be useful for many other users too, especially those from enterprise environments.
[FIPS 140-3 Compliance](https://go.dev/doc/security/fips140) document, which is part of the Go 1.24 release defines runtime GODEBUG runtime toggles for [FIPS](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards) compliance.
SHA-1 is not a FIPS-approved algorithm, so using it in integrations with Redis complicates compliancy audit. And also Go runtime panics in case of using Redis Lua with `fips140=only` mode: https://cs.opensource.google/go/go/+/refs/tags/go1.24.2:src/crypto/sha1/sha1.go;l=273
This PR adds support to avoid SHA-1 usage by introducing a couple of new constructors for Lua scripts: …
> Support Lua scripts without SHA-1 usage for FIPS compliancy

- client.go
- client_test.go
follow-up #727
We overlooked to handle transaction block when connection expired.
> Check transaction block when using connection lifetime

- cluster.go
- cluster_test.go
- sentinel.go
- sentinel_test.go
This is follow-up PR regarding #727 .
See https://github.com/redis/rueidis/pull/727#issuecomment-2823047261.
> Add retry logic of connection lifetime to cluster client and sentinel client

- README.md
- pipe.go
- pipe_test.go
- pubsub.go
- pubsub_test.go
This PR adds the `WithOnSubscriptionHook` function for users to carry a hook to the context for the `Receive` method, allowing users to inject custom logic on subscription events. This approach avoids breaking the current interface.
Use `rueidis.WithOnSubscriptionHook` when you need to observe subscribe / unsubscribe confirmations that the server sends. The hook can be triggered multiple times because the client may automatically reconnect and resubscribe.
```go
ctx := rueidis.WithOnSubscriptionHook(context.Background(), func(s rueidis.PubSubSubscription) {
// This hook runs in the pipeline goroutine. If you need to perform
// heavy work or invoke additional commands, do it in another
// goroutine to avoid blocking the pipeline, for example:
//   go func() {
//       // long work or …
```
> feat: add the new WithOnSubscriptionHook for the Receive method

- README.md
Changed `valkey.Commands` to `rueidis.Commands` in the pinned commands example.
> Update package name in README example

- rueidiscompat/command.go
- rueidiscompat/command_test.go
This PR adds support for the new Redis client information fields introduced in redis/redis#13944.
- `TotalNetIn` (int64): total network bytes read from the client connection
- `TotalNetOut` (int64): total network bytes sent to the client connection  
- `TotalCmds` (int64): number of commands executed by the client connection
https://github.com/redis/rueidis/issues/872
> feat: Add TotalNetIn, TotalNetOut, and TotalCmds fields to ClientInfo

- internal/cmds/iter.go
- internal/cmds/iter_test.go
- Added `hsetex` method to the `iter.go`.
- Created a new test case for it.
> Support FieldValueIter for Hsetex

- helper.go
- helper_test.go
Both inner and outer `for` must be exited when `yield` returns `false`.
> fix: correctly handle early exit in `Scanner` iterators

- README.md
This PR updates the README to document the memory usage of per-connection read and write buffers.
- Adds description of `ClientOption.ReadBufferEachConn` (default: 0.5 MiB)
- Adds description of `ClientOption.WriteBufferEachConn` (default: 0.5 MiB)
- Provides example code snippet showing how to configure these options
Closes #885
> docs: mention ReadBufferEachConn and WriteBufferEachConn in memory considerations
